config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :posts, only: [ :index, :new, :create ]
  resources :likes, only: [ :create ]
  resources :flags, only: [ :create ]

  get '/about' => 'pages#about', as: 'about'

  mount Attachinary::Engine => "/attachinary"

  devise_for :users, controllers: {registrations: "users/registrations"}
  root to: 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flag.rb
class Flag < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post }


end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: true

  validates :user_id, uniqueness: { scope: :post }
end

app/models/post.rb
class Post < ApplicationRecord
  include PgSearch
  pg_search_scope :search_by_content, against: [ :id, :content ]

  before_validation :define_SO_ASO

  belongs_to :school
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :flags, dependent: :destroy

  validates :content, length: { minimum: 3, maximum: 150 }, presence: true, allow_blank: false
  validate :is_post_SO_or_ASO_or_both


  def define_SO_ASO
    if content.match(/^ASO|(ASO)/)
      self.is_antishoutout = true
    elsif content.match(/^SO|[^A](SO)/)
      self.is_shoutout = true
    end
  end


  def is_post_SO_or_ASO_or_both
    return if self.is_shoutout || self.is_antishoutout
    errors.add(:content, "You must use either 'SO' or 'ASO' somewhere in your post")
  end

  def number_of_likes
    likes.count
  end

  def flagged?
    flags.present?
  end


end

app/models/school.rb
class School < ApplicationRecord
  has_many :users
  has_many :posts
  has_attachment :logo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, uniqueness: true, format: { with: /(@wisc.edu|@colum.edu)/, message: "You must enter a valid school email of your chosen school" }
  validates :school, presence: true

  validate :check_email_for_chosen_school

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :flags, dependent: :destroy
  belongs_to :school

  def check_email_for_chosen_school
    return if email.include?(school.email_domain_name)
    errors.add(:email, 'should correspond to the chosen school')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!



end

app/controllers/flags_controller.rb
class FlagsController < ApplicationController

  def create
    current_user.flags.create(post_id: params[:post_id])
    @post = Post.find(params[:post_id])
    respond_to do |format|
      format.html { redirect_to posts_path }
      format.js  # <-- will render `app/views/reviews/create.js.erb`
    end

  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    current_user.likes.create(post_id: params[:post_id])
    @post = Post.find(params[:post_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :about ]

  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def index
    type = params[:index_type]
    school = current_user.school
    @post = current_user.posts.new
    @posts = if params[:query].present?
        school.posts.search_by_content(params[:query])
      elsif type == 'SO'
        school.posts.where(is_shoutout: true).order("id DESC")
      elsif type == 'ASO'
        school.posts.where(is_antishoutout: true).order("id DESC")
      elsif type == 'POP'
        order_popularity
      else
        school.posts.order("id DESC")
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @post = current_user.posts.create(post_params)
    # @post = Post.new
    # @post.save
    respond_to do |format|
      format.html do
        flash[:alert] = @post.errors.full_messages if @post.errors.present?
        redirect_to posts_path(@post)
      end
      format.js  # <-- will render `app/views/reviews/create.js.erb`
    end
  end

  private

  def post_params
    params.require(:post).permit(:content, :school_id, :likes_count)
  end

  def order_popularity
    @posts_per_like = current_user.school.posts.order(likes_count: :desc)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include EmojiHelper
end

app/helpers/emoji_helper.rb
module EmojiHelper
  def emojify(content)
    h(content).to_str.gsub(/:([\w+-]+):/) do |match|
      if emoji = Emoji.find_by_alias(match.gsub(':', ''))
        %(<img alt="#$1" src="#{image_path("emoji/#{emoji.image_filename}")}" style="vertical-align:middle" width="20" height="20" />)
      else
        match
      end
    end.html_safe if content.present?
  end
end


# This has a list of emojis (some won't work)
# http://www.webpagefx.com/tools/emoji-cheat-sheet/

app/helpers/flags_helper.rb
module FlagsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoutOut</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %> <!-- Append this after the main `javascript_include_tag`. -->

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes'  %>
    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="text-center">
    <h1>About ShoutOuts</h1>
  </div>

  <h3>
    Shouts-Outs mission is to give school students the ability to share stories with one another without subject to online harassment.
  </h3>
  <strong>Basic Terms</strong>
  <ol>
    <li>
      You must be a university student with an official school email to use the service.
    </li>
    <li>
      You are responsible for keeping your password secret and secure.
    </li>
    <li>
      You must not defame, stalk, bully, abuse, harass, threaten, impersonate or intimidate people or entities and you must not post private or confidential information via the Service, including, without limitation, your or any other person's credit card information, social security or alternate national identity numbers, non-public phone numbers or non-public email addresses - your account will be suspended!.
    </li>
    <li>
      You may not use the Service for any illegal or unauthorized purpose. You agree to comply with all laws, rules and regulations (for example, federal, state, local and provincial) applicable to your use of the Service and your Content, including but not limited to, copyright laws.
    </li>
    <li>
      You are solely responsible for your conduct and any data, text, information and other content or materials (collectively, "Content") that you submit, post on or via the Service.
    </li>
    <li>
      You must not use harassing communications, first and last names, or offensive behavior.
      Violation of these Terms of Use may, result in termination of your ShoutOut account. You understand and agree that ShoutOut cannot and will not be responsible for the Content posted on the Service and you use the Service at your own risk. If you violate the latter or spirit of these Terms of Use, or otherwise create risk or possible legal exposure for ShoutOut, we can stop providing all or part of the Service to you.
    </li>
    <li>
      ShoutOut does not claim ownership of any Content that you post on or through the Service. Instead, you hereby grant to ShoutOut a non-exclusive, fully paid and royalty-free, transferable, sub-licensable, worldwide license to use the Content that you post on or through the Service, subject to the Service's Privacy Policy,
    </li>
    <li>
      You agree that ShoutOut is not responsible for, and does not endorse, Content posted within the Service.
    </li>
    <li>
      ShoutOut can prescreen, monitor, edit, or remove any Content. If your Content violates these Terms of Use, you may bear legal responsibility for that Content.
    </li>
    <li>
      We respect other people's rights, and expect you to do the same.
      We provide you with tools to help you protect your intellectual property rights.
      If you repeatedly infringe other people's intellectual property rights, we will disable your account when appropriate.
    </li>
    <li>
      You can like a post by clicking the <i class="fa fa-heart-o" aria-hidden="true"></i>
    </li>
    <li>
      You kan report a post by clicking the <i class="fa fa-flag" aria-hidden="true"></i> and then the admin wil check if the post is against ShoutOuts rules, and delete the post if so. If the post is considered appropriate and we deem it acceptable, then the flag option is removed, and cannot be subjected to further flagging.
    </li>
  </ol>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url(<%= image_path "background.jpg"%>);">
  <div class="banner-content">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-8">
        <div class="headline">
          <h1>Welcome to ShoutOut.</h1>
          <h2>Connect with your friends and other fascinating people at school. Get in-the-moment updates.</h2>
          <h2>Get a live feed of what people are saying in your local community.</h2>
        </div>
      </div>
      <div class="col-xs-6 col-md-4">
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="row footer">
  <div class="col-xs-4">
    <ul class="list-inline">
      <li> <%= social_share_button_tag() %> </li>
    </ul>
  </div>
  <div class="col-xs-8 text-right list-inline name">
    <%= link_to root_path, class: "logo_small" do %>
      <%= image_tag "logo_2.png" %>
    <% end %>
      ShoutOut
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon <%= 'navbar-wagon-fixed' if action_name == "index"  %>" >
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo_2.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

    <!-- Searchform -->
     <%= form_tag posts_path, class: "form-inline search-form", method: :get do %>
       <input type="text" name="query" id="query" class="form-control" placeholder="Search content or id">
       <button type="submit" class="btn btn-default">
        <i class="fa fa-search" aria-hidden="true"></i>
       </button>
      <% end %>


      <!-- dropdown -->
      <div class="navbar-wagon-item">

        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

            <li>
              <%= link_to about_path do %>
                <i class="fa fa-question" aria-hidden="true"></i>  <%= t(".profile", default: "About us") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% end %>


  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">

    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

        <li>
          <%= link_to about_path do %>
            <i class="fa fa-question" aria-hidden="true"></i>  <%= t(".profile", default: "About us") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_post.html.erb
<div class="post-section-2 gray-border">
<span data-flag-post-id="<%= post.id %>">
  <% if post.flags.empty? || post.approved %>
  <div class="id-badge">
  <%= social_share_button_tag([post.id, post.content]) %>
    <p><span class="the-id">#<%= post.id %></span> <i class="fa fa-calendar" aria-hidden="true"> </i> <span class="the-dates"><%= post.created_at.strftime("%A - %b %e, %Y | %I:%M %p ") %></span></p>
  </div>
    <p class="main-content"><%= emojify(post.content) %></p>
<hr>
    <div class="row post-fontawesome">
      <%= link_to likes_path(post_id: post.id), method: :post, remote: true, class: "heart-stuff" do %>
        <% if post.likes.count < 1 %>
        <span heart-post-id="<%= post.id %>">
        <i class="fa fa-heart-o" aria-hidden="true"></i>
        </span>
        <span data-post-id="<%= post.id %>">
          <%= post.likes.count %>
        </span>
        <% else %>
        <span heart-post-id="<%= post.id %>">
        <i class="fa fa-heart" aria-hidden="true"></i>
        </span>
        <span data-post-id="<%= post.id %>">
          <%= post.likes.count %>
        </span>
        <% end %>
      <% end %>
      <%= link_to flags_path(post_id: post.id), method: :post, remote: true do %>
        <i class="fa fa-flag alignright" aria-hidden="true"></i>
      <% end unless post.approved %>
    </div>
  <% else %>
    <h5><em>This post is temporarily flagged -pending review</em></h5>
  <% end %>
</span>
</div>